steps:
  - id: "Build rails-app"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/rails-app", "."]

  - id: "Deploy kubernetes"
    name: "gcr.io/cloud-builders/kubectl"
    args:
      - set
      - image
      - deployment
      - rails-app=gcr.io/$PROJECT_ID/rails-app:$SHORT_SHA
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=nodejs-cluster"

images:
  - gcr.io/$PROJECT_ID/rails-app:$SHORT_SHA
  - gcr.io/$PROJECT_ID/rails-app
