version: "3"
services:
  web:
    build:
      context: ./
      args:
        RAILS_MASTER_KEY: 4ddc3f115f00ee39976a014827314652
      dockerfile: ./docker/production/rails/Dockerfile
    image: dockerize-rails-production
    container_name: web
    command: 'bash -c "bundle exec rake db:create db:migrate && bundle exec rails server -p 3000 -b 0.0.0.0"'
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: 4ddc3f115f00ee39976a014827314652
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: ""
      RAILS_LOG_TO_STDOUT: "true"
      # sidekiq redis
      # https://github.com/mperham/sidekiq/wiki/Using-Redis
      REDIS_PROVIDER: REDISGREEN_URL
      REDISGREEN_URL: redis://redis:6379/0
      NODE_ENV: production

  worker:
    image: rails-docker-production
    container_name: worker
    command: bundle exec sidekiq -q default -q mailers
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: 4ddc3f115f00ee39976a014827314652
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: ""
      RAILS_LOG_TO_STDOUT: "true"
      # sidekiq redis
      # https://github.com/mperham/sidekiq/wiki/Using-Redis
      REDIS_PROVIDER: REDISGREEN_URL
      REDISGREEN_URL: redis://redis:6379/0
      NODE_ENV: production

  db:
    image: postgres:9.5.9
    # ports:
    #   - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data:delegated

  nginx:
    build:
      context: ./docker/production/nginx
      args:
        WEBAPP_HOST: http://localhost:3000
      dockerfile: ./Dockerfile
    image: dockerize-nginx-production
    ports:
      - "80"
    depends_on:
      - web
    network_mode: "host"

  redis:
    image: redis
    # ports:
    #   - "6379:6379"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080

volumes:
  postgresql:
# USAGE

# docker-compose up
