version: '3'
services:
  web:
    build:
      context: ./
      args:
        RAILS_MASTER_KEY: ea3aaacc43f832b6e9049e61211561dc
      dockerfile: ./docker/production/rails/Dockerfile
    container_name: web
    command: 'bash -c "bundle exec rake db:migrate && bundle exec rails server -p 3000 -b 0.0.0.0"'
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: ea3aaacc43f832b6e9049e61211561dc
      RAILS_LOG_TO_STDOUT: "true"
      # sidekiq redis
      # https://github.com/mperham/sidekiq/wiki/Using-Redis
      REDIS_PROVIDER: REDISGREEN_URL
      REDISGREEN_URL: redis://redis:6379/0
      NODE_ENV: production

  worker:
    build:
      context: ./
      args:
        RAILS_MASTER_KEY: ea3aaacc43f832b6e9049e61211561dc
      dockerfile: ./docker/production/rails/Dockerfile
    container_name: worker
    command: bundle exec sidekiq -q default -q mailers
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: ea3aaacc43f832b6e9049e61211561dc
      RAILS_LOG_TO_STDOUT: "true"
      # sidekiq redis
      # https://github.com/mperham/sidekiq/wiki/Using-Redis
      REDIS_PROVIDER: REDISGREEN_URL
      REDISGREEN_URL: redis://redis:6379/0
      NODE_ENV: production

  db:
    image: postgres:9.5.9
    # ports:
    #   - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data:delegated

  nginx:
    build:
      context: ./docker/production/nginx
      args:
        WEBAPP_HOST:  http://web:3000
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - web

  redis:
    image: redis
    # ports:
    #   - "6379:6379"
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080

volumes:
  postgresql:

# USAGE

# docker-compose up

# enter in the container for run rails console or rake tasks
# docker-compose run web bash

# attach the container when use binding.pry
# docker attach web

# when run rails generator you need to run
# sudo chown -R $USER:$USER $(ls | grep -v volumes)
