apiVersion: v1
kind: Service
metadata:
  name: rails-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rails-nginx
  type: LoadBalancer
status:
  loadBalancer: {}
