apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 2
  selector:
    app: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:9.5.9
        name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresqldata
      volumes:
      - name: postgresqldata
