---
  kind: Job
  apiVersion: batch/v1
  metadata:
    generateName: rails-job-rake-about
  spec:
    backoffLimit: 2
    activeDeadlineSeconds: 10
    template:
      spec:
        containers:
          - image: devmasx/rails-sqlite
            name: rails
            command: ["rake", "about"]
            env:
              - name: SECRET_KEY_BASE
                value: "88bd35ae12965db0f0018e8c70849263fd7f2f176d586912c71b106f0a5adf7c7826b28184b57ac194a4c7ff41fedbd12f310c930dc9ec901485089fc95cc848"
            # envFrom:
            #   - configMapRef:
            #       name: rails-config
            #   - secretRef:
            #       name: rails-secrets
        restartPolicy: Never

# kubectl create -f kubernetes/rails-job.yaml
