kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: rails-nginx
  name: rails-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rails-nginx
  template:
    metadata:
      labels:
        app: rails-nginx
    spec:
      containers:
        - image: devmasx/dockerize-nginx-production
          name: nginx
        - image: devmasx/dockerize-rails-production
          name: rails
          envFrom:
            - configMapRef:
                name: rails-config
            - secretRef:
                name: rails-secrets
