name: deploy to k8s with cache

on:
  push:
    branches:
      - "master"
      - "gcloud-k8s"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "271.0.0"
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: gcloud auth configure-docker
      - uses: devmasx/cached-docker-build-push@master
        with:
          image_name: gcr.io/docker-rails-258302/rails-sqlite
          cache_image_name: gcr.io/docker-rails-258302/rails-sqlite--builder
          cache_stage_target: development
