name: deploy to k8s with cache

on:
  push:
    branches:
      - "gcloud-k8s"
env:
  GCP_PROJECT: docker-rails-258302
  GKE_ZONE: us-central1-a
  GKE_CLUSTER: example-gke-cluster
  IMAGE: gcr.io/docker-rails-258302/rails-sqlite
  SERVICE_DEPLOYMENT: deployment/rails-nginx
  CONTAINER_1: rails

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "271.0.0"
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - run: gcloud auth configure-docker

      - uses: devmasx/cached-docker-build-push@master
        with:
          image_name: $IMAGE

      - name: Deploy K8s
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GCP_PROJECT
          kubectl set image $SERVICE_DEPLOYMENT $CONTAINER_1=$IMAGE:$GITHUB_SHA
          kubectl rollout status $SERVICE_DEPLOYMENT
