name: Rails

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Install gems
        run: |
          apt-get update
          apt-get install -y postgresql-client libpq-dev
          bundle install
      - name: Brakeman report
        run: |
          bundle exec brakeman report -json > /tmp/brakeman.json
      - name: Brakeman
        uses: devmasx/github-action-ruby-brakeman@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          REPORT_PATH: /tmp/brakeman.json
