name: Rails

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # - name: Set up Ruby 2.6
      #   uses: actions/setup-ruby@v1
      #   with:
      #     ruby-version: 2.6.x

      - name: Brakeman
        uses: devmasx/github-action-ruby-brakeman@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_APP_TOKEN}}
      - name: Fail
        run: |
          exit() 1
