name: Rails

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # - uses: actions/setup-ruby@v1
      #   with:
      #     ruby-version: '2.x'
      - uses: actions/download-artifact@master
        with:
          name: coverage-report
          path: last-coverage
      # - uses: devmasx/coverage-check-action@master
      #   with:
      #     name: ruby-simplecov
      #     path: coverage/.last_run.json
      - run: cat last-coverage/.last_run.json
