name: Rails

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # - uses: actions/setup-ruby@v1
      #   with:
      #     ruby-version: '2.x'
      - uses: actions/upload-artifact@master
        with:
          name: coverage-report
          path: coverage
      - uses: devmasx/brakeman-linter-action@coverage-check
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          REPORT_PATH: coverage/.last_run.json
