name: Rails

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # - uses: actions/setup-ruby@v1
      #   with:
      #     ruby-version: '2.x'
      - uses: actions/upload-artifact@master
        with:
          name: coverage-report
          path: coverage
      - run: cat coverage/.last_run.json
      - uses: devmasx/coverage-check-action@coverage-check
        with:
          result_path: coverage/.last_run.json
          token: ${{secrets.GITHUB_TOKEN}}
          type: simplecov
          min_coverage: 80
